spring.application.name=provider-service

# ===============================
# Server
# ===============================
<<<<<<< HEAD
server.port=${SERVER_PORT:8082}
=======
server.port=${PORT:8082}
>>>>>>> d3ccc376880c03979499075e392054b9ebad8978


# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:5}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:1}


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public


# ===============================
# Swagger
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# ===============================
# JWT
# ===============================
<<<<<<< HEAD
jwt.secret=${JWT_SECRET}
=======
jwt.secret=${JWT_SECRET:HomeServeProviderJwtSecretKey2026SecureForDevelopmentOnly}
>>>>>>> d3ccc376880c03979499075e392054b9ebad8978
jwt.expiration=${JWT_EXPIRATION:86400000}


# ===============================
# Eureka
# ===============================
<<<<<<< HEAD
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
=======
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=${EUREKA_ENABLED:false}
eureka.client.fetch-registry=${EUREKA_ENABLED:false}
>>>>>>> d3ccc376880c03979499075e392054b9ebad8978
eureka.instance.prefer-ip-address=true

# ===============================
# Internal Microservice Security
# ===============================

homeserve.internal.api-key=${INTERNAL_API_KEY}